# Generated by Django 3.0.2 on 2020-01-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
