# Generated by Django 3.0.2 on 2020-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Toto je book description', max_length=500),
            preserve_default=False,
        ),
    ]
